# Console via UART0 (USB-serial do DAPLINK)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y

# GPIO — gpio_pin_configure / gpio_pin_set / gpio_pin_get
CONFIG_GPIO=y

# Desabilita driver Zephyr de PWM: TPM2 é controlado diretamente via pwm_z42
CONFIG_PWM=n
