; Entrega 1 — Pisca LED
; Build + flash: pio run -t upload
; Monitor serial: pio device monitor --baud 115200

[platformio]
description = Entrega 1 — Pisca LED vermelho via GPIO Zephyr

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
