; Entrega 5-1 — HC-SR04 + PWM radar (Zephyr híbrido)
; Build + flash: pio run -t upload
; Monitor: pio device monitor --baud 115200

[platformio]
description = Entrega 5-1 — HC-SR04 + TPM2 via Zephyr + pwm_z42

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
build_flags = -I../include
