; Entrega 3 — bare-metal
; Build real: make   |   IDE/IntelliSense: PlatformIO

[platformio]
description = Entrega 3

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
build_flags = -I../include
