; Entrega 5 — bare-metal + pwm_z42 (Prof. Rehder)
; Build real: make   |   IDE/IntelliSense: PlatformIO

[platformio]
description = Entrega 5 — HC-SR04 + PWM radar

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
build_flags = -I../include
;upload_protocol = cmsis-dap
;debug_tool = cmsis-dap
