; Entrega 6 — Threads
; Build + flash: pio run -t upload
; Monitor: pio device monitor --baud 115200

[platformio]
description = Atividade 6 — Threads (K_THREAD_DEFINE)

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
; só para dizer que dá para configurar
; board_build.cmake_extra_args = -DCONF_FILE=zephyr/prj.conf
