; Entrega 4 — bare-metal
; Build real: make   |   IDE/IntelliSense: PlatformIO

[platformio]
description = Entrega 4

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
build_flags = -I../include
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
