; IDE + IntelliSense — build real: make
; Entrega 4: bare-metal, sem framework Zephyr

[platformio]
description = Entrega 4

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
src_dir = .
src_filter = +<main.c>
build_flags = -I../include
