; Entrega 7 — Shared Resources
; Build + flash: pio run -t upload
; Monitor: pio device monitor --baud 115200

[platformio]
description = Atividade 7 — Shared Resources (k_mutex)

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
