; Entrega 7 — Shared Resources
; Build + flash: pio run -t upload
; Monitor: pio device monitor --baud 115200

[platformio]
description = Atividade 7 — Shared Resources (k_mutex)

[env:frdm_kl25z]
platform = freescalekinetis
board = frdm_kl25z
framework = zephyr
board_build.cmake_extra_args = -DCONF_FILE=zephyr/prj.conf
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
